name: Deploy to Private Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install OpenVPN
        run: |
          sudo apt update
          sudo apt install -y openvpn

      - name: Create OpenVPN Credentials File
        run: |
          echo "${{ secrets.VPN_USERNAME }}" > vpn-auth.txt
          echo "${{ secrets.VPN_PASSWORD }}" >> vpn-auth.txt
          chmod 600 vpn-auth.txt

      - name: Start OpenVPN Connection
        run: |
          sudo openvpn --config test.ovpn --auth-user-pass vpn-auth.txt --daemon
          sleep 15  # Wait for VPN to establish

      - name: Verify VPN Connection
        run: ping -c 4 192.168.0.179  # Replace with your private server IP
