name: Build & Deploy
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy BK apps
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.HOST}} # IP address of the server you wish to ssh into
          key: ${{secrets.KEY}} # Private or public key of the server
          username: ${{ secrets.USERNAME }}
          script: |
            cd /home/ubuntu
            git clone git@github.com:yaswanth507/simple-php-website.git
            sudo mv simple-php-website /var/www/html 
            
     
