name: Deploy to Private Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install OpenVPN
        run: |
          sudo apt update
          sudo apt install -y openvpn

      - name: Start OpenVPN Connection
        run: |
          sudo openvpn --config test.ovpn --daemon
          sleep 10  # Wait for VPN to establish

      - name: Check VPN Connection
        run: ip a  # Verify if VPN interface is up
